### ISSUE TITLE
BPW Firefox Clean Germany 

### ISSUE THREAD

**Issue by ChrisPastCBU** [qnoum/bypass-paywalls-firefox-clean-magnolia1234#1]
on Chrome i get the sites, --  but not on Firefox.
www.wp.de
www.wr.de
all Funke Mediengroup , the browser change ist a little bit annoying.
krgds
Chris

**Comment by qnoum** [comment]
Same by me, only encrypted gibberish is visible in no style mode in FF on both sites.

**Comment by ChrisPastCBU** [comment]
can you fix it??

**Comment by ChrisPastCBU** [comment]
wrong button :-)

**Comment by qnoum** [comment]
You should open this issue at gitlab and ask magnolia, link on the homepage:
https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean

**Comment by qnoum** [comment]
actually I just opened it, you are welcome to discuss it there: 
https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean/-/issues/20
